# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTest0001():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_test0001(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(593, 693)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("taobao")
    self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "【淘宝网】-品牌汇聚_淘我喜欢").click()
    self.vars["window_handles"] = self.driver.window_handles
    [object Object]
    self.vars["win4874"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win4874"])
    self.driver.switch_to.window(self.vars["root"])
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.window(self.vars["win4874"])
    element = self.driver.find_element(By.ID, "city__1")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "city__1").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#ItemWrapper > .item:nth-child(2) img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(7) img").click()
    self.vars["win8106"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8106"])
    self.driver.execute_script("window.scrollTo(0,300)")
    self.driver.find_element(By.ID, "sufei-dialog-close").click()
    element = self.driver.find_element(By.ID, "J_LinkBuy")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,505.5)")
    self.driver.find_element(By.ID, "J_LinkBuy").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a > img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "J_ImgBooth")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tb-selected img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".tb-selected img").click()
    element = self.driver.find_element(By.ID, "J_ImgBooth")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
  
